# Generated by Django 5.1 on 2024-08-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
    ]
