# Generated by Django 4.2.15 on 2024-08-21 09:43

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('single_page', '0002_user_is_phone_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authsms',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='휴대폰 번호')),
                ('auth_number', models.IntegerField(null=True, verbose_name='인증 번호')),
                ('is_phone_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_sms',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_telecom',
        ),
    ]
